"""darpalyft: DARPA LIFT drone design optimization and continual learning package."""
from .core import (
    MaterialType,
    MATERIAL_DENSITY,
    MATERIAL_STRENGTH,
    DroneComponent,
    DroneDesign,
    PhysicsConstraints,
    TaskDomain,
    TaskRecord,
    TaskSequence,
    motor_thrust_n,
    structural_safety_factor,
    payload_capacity,
    DesignOptimizer,
)
from .evaluate import (
    backward_transfer,
    forward_transfer,
    continual_learning_score,
    plasticity_score,
    stability_score,
    domain_drift_penalty,
    is_feasible,
    design_score,
    pareto_designs,
    optimization_report,
)

__all__ = [
    "MaterialType",
    "MATERIAL_DENSITY",
    "MATERIAL_STRENGTH",
    "DroneComponent",
    "DroneDesign",
    "PhysicsConstraints",
    "TaskDomain",
    "TaskRecord",
    "TaskSequence",
    "motor_thrust_n",
    "structural_safety_factor",
    "payload_capacity",
    "DesignOptimizer",
    "backward_transfer",
    "forward_transfer",
    "continual_learning_score",
    "plasticity_score",
    "stability_score",
    "domain_drift_penalty",
    "is_feasible",
    "design_score",
    "pareto_designs",
    "optimization_report",
]
